<a href="https://colab.research.google.com/github/RomeroCruzJuanPablo/RomeroCruz-JuanPablo/blob/main/Class%20Excercises/06_Numpy_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 6. Numpy indexing

Often we need to extract some information from a Pandas DataFrame. Here also, Pandas inherits many of the approaches used in Numpy. Therefore we start here by very briefly showing how to proceed with plain arrays before looking at the more complex DataFrames.

Note that Numpy indexing is very powerful and that we cover here only a tiny fraction of this topic. To learn more you can for example the [Numpy reference](https://numpy.org/doc/stable/reference/arrays.indexing.html#indexing).

In [1]:
import numpy as np

We first create an array:

In [2]:
my_array = np.random.normal(size=10)
my_array

array([ 0.14187897, -0.26062403, -0.22994508, -0.40156951, -0.68940422,
       -0.75886135,  0.65040664,  0.98916319, -0.72645124,  1.05036553])

## Extracting and setting elements

The standard way to extract information from an array is to used the square parenthesis (bracket) notation. If we want for example to extract the second element of the array we write:



In [3]:
my_array[1]

-0.26062402515106603

Remember that **we start counting from 0** in Python, which is why the *second* element has index 1.

We can extend the notation and extract a range of elements by using the ```from_index:to_index (excluded)``` notation. Here ```excluded``` means that the **last index** specified is **not included**. For example if we want to recover elements with indices from 1 to 3 we write:

In [4]:
my_array[1:4]

array([-0.26062403, -0.22994508, -0.40156951])

We can also set values in the array in the same maner. For example let's set the above elements to 10:

In [5]:
my_array[1:4] = 10

In [6]:
my_array

array([ 0.14187897, 10.        , 10.        , 10.        , -0.68940422,
       -0.75886135,  0.65040664,  0.98916319, -0.72645124,  1.05036553])

Note that you can sometimes simplify the notation. For example if you want to extract all elements from the 4th one **to the last one**, you don't have to specify the last index, you can simply replace it by ```:```:


In [8]:
my_array[4::]

array([-0.68940422, -0.75886135,  0.65040664,  0.98916319, -0.72645124,
        1.05036553])

In [9]:
my_array[4:]

array([-0.68940422, -0.75886135,  0.65040664,  0.98916319, -0.72645124,
        1.05036553])

## Higher dimensions

We have seen before that we can create arrays with more than one dimension (think e.g. of the pixels of an image). For example:

In [10]:
array2D = np.random.normal(size=(3,5))
array2D

array([[-0.50269892, -0.80494521,  0.17661695, -0.7859049 , -2.87883332],
       [ 0.71944351,  1.59792888,  0.02509248, -0.40304565, -1.65776884],
       [-0.26557607, -0.17103007, -0.72038761,  1.92990236,  0.01320477]])

The indexing system works in the same way here. We just have to specify now for each dimension which rows/columns we want to extract with ```my_array[start_row:end_row, start_column:end_column]```:

In [11]:
array2D[1:3, 0:2]

array([[ 0.71944351,  1.59792888],
       [-0.26557607, -0.17103007]])

Here again, we can simplify the notation. If we want to select a few rows but **want to keep all columns**, we can again use the ```:``` notation like this:

In [12]:
array2D[1:3, :]

array([[ 0.71944351,  1.59792888,  0.02509248, -0.40304565, -1.65776884],
       [-0.26557607, -0.17103007, -0.72038761,  1.92990236,  0.01320477]])

## Working with sub-parts

Using indexing, we can also create a smaller array that we want to work on specifically. For example let's say we are only interested in the 6th to 8th element. We can **extract** it and **asign** it to a new array:

In [13]:
sub_array = my_array[7:10]

In [14]:
my_array

array([ 0.14187897, 10.        , 10.        , 10.        , -0.68940422,
       -0.75886135,  0.65040664,  0.98916319, -0.72645124,  1.05036553])

In [15]:
sub_array

array([ 0.98916319, -0.72645124,  1.05036553])

Let's now modify an element of this subarray:

In [16]:
sub_array[0] = 100

Let's check that ```sub_array``` has indeed changed:

In [17]:
sub_array

array([100.        ,  -0.72645124,   1.05036553])

Let's now also have a look at the original array:

In [18]:
my_array

array([  0.14187897,  10.        ,  10.        ,  10.        ,
        -0.68940422,  -0.75886135,   0.65040664, 100.        ,
        -0.72645124,   1.05036553])

**The value in the original array has changed too!**. The reason is that the slicing of the array **does not create an independent sub-array**. It is still linked to the original one. Depending on the types of modification, you might or might not encounter this problem. To be on the safe side, explicitely create a **copy** when creating a sub-array. Like that it will be independent from the original one: 

In [19]:
sub_array = my_array[7:10].copy()
sub_array[0] = 200

In [20]:
sub_array

array([200.        ,  -0.72645124,   1.05036553])

In [21]:
my_array

array([  0.14187897,  10.        ,  10.        ,  10.        ,
        -0.68940422,  -0.75886135,   0.65040664, 100.        ,
        -0.72645124,   1.05036553])

## Boolean indexing

Instead of using numerical indices to extract values from the array, we can also select them by some criteria. Let's create a new random array:

In [22]:
my_array2 = np.random.normal(size=10)
my_array2

array([-0.5094085 ,  1.64010904, -0.37857419, -0.69257633, -1.15305252,
       -1.14785391, -1.01617137,  0.24406263,  0.29056254,  1.28322148])

How to proceed now if we for example only want to recover the elements that are larger than 0 ?

Let's try to see what happens when we just write it down as we would in regular mathemetics:

In [23]:
my_array2 > 0

array([False,  True, False, False, False, False, False,  True,  True,
        True])

We see that the output is again an array, but instead of being filled with numbers, it contains only ```False``` and ```True```. Those values also exist in plain Python and are called booleans. For example:

In [24]:
a = 3
a > 10

False

We can now create an actual boolean array:

In [25]:
bool_array = my_array2 > 0
bool_array

array([False,  True, False, False, False, False, False,  True,  True,
        True])

We can now use this **boolean array** ```bool_array``` to extract values from any array of the same size. Imagine that you superpose ```bool_array``` to another array ```value_array``` and only select those values in ```value_array``` which are ```True``` in ```bool_array```. Naturally we can do this with the original array itself. Instead of passing and index ```my_array[i]``` we pass the entire ```bool_array```:

In [26]:
from IPython.display import Image
Image(url='https://github.com/guiwitz/ISDAwPython_day2/raw/master/images/logical_indexing.jpeg',width=700)

In [27]:
my_array2[bool_array] 

array([1.64010904, 0.24406263, 0.29056254, 1.28322148])

Naturally this output array is much smaller than the original one as it only contains the values larger than 0.

## Exercise

1. Create a numpy array with values from 0 to 10 in steps of 0.5
2. Extract the the last three elements of the array using slicing.
3. Apply a cosine function to the full array created in (1.) and store the output in a new array.
4. Create a boolean array telling which values in the array from (3.) are smaller than 0.
5. Recover only those values in a new array via indexing.

In [31]:
ar1=np.arange(0,10,0.5)
ar1

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [33]:
ar2=ar1[-3:]
ar2

array([8.5, 9. , 9.5])

In [35]:
cos=np.cos(ar1)
cos

array([ 1.        ,  0.87758256,  0.54030231,  0.0707372 , -0.41614684,
       -0.80114362, -0.9899925 , -0.93645669, -0.65364362, -0.2107958 ,
        0.28366219,  0.70866977,  0.96017029,  0.97658763,  0.75390225,
        0.34663532, -0.14550003, -0.6020119 , -0.91113026, -0.99717216])

In [36]:
bol_ar2=cos<0

In [37]:
cos[bol_ar2]

array([-0.41614684, -0.80114362, -0.9899925 , -0.93645669, -0.65364362,
       -0.2107958 , -0.14550003, -0.6020119 , -0.91113026, -0.99717216])